// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParksAPI.Models;

namespace ParksAPI.Solution.Migrations
{
    [DbContext(typeof(ParksContext))]
    partial class ParksContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ParksAPI.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Miles");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Miles = 882,
                            Name = "Yellowstone National Park",
                            State = "Wyoming"
                        },
                        new
                        {
                            ParkId = 2,
                            Miles = 1070,
                            Name = "Zion National Park",
                            State = "Utah"
                        },
                        new
                        {
                            ParkId = 3,
                            Miles = 722,
                            Name = "Yosemite National Park",
                            State = "California"
                        },
                        new
                        {
                            ParkId = 4,
                            Miles = 3360,
                            Name = "Acadia National Park",
                            State = "Maine"
                        },
                        new
                        {
                            ParkId = 5,
                            Miles = 819,
                            Name = "Grand Teton National Park",
                            State = "Wyoming"
                        },
                        new
                        {
                            ParkId = 6,
                            Miles = 991,
                            Name = "Arches National Park",
                            State = "Utah"
                        },
                        new
                        {
                            ParkId = 7,
                            Miles = 1096,
                            Name = "Joshua Tree National Park",
                            State = "California"
                        },
                        new
                        {
                            ParkId = 8,
                            Miles = 829,
                            Name = "Sequoia National Park",
                            State = "California"
                        },
                        new
                        {
                            ParkId = 9,
                            Miles = 647,
                            Name = "Glacier National Park",
                            State = "Montana"
                        },
                        new
                        {
                            ParkId = 10,
                            Miles = 987,
                            Name = "Capitol Reef National Park",
                            State = "Utah"
                        },
                        new
                        {
                            ParkId = 11,
                            Miles = 1254,
                            Name = "Badlands National Park",
                            State = "South Dakota"
                        },
                        new
                        {
                            ParkId = 12,
                            Miles = 1306,
                            Name = "Great Sand Dunes",
                            State = "Colorado"
                        },
                        new
                        {
                            ParkId = 13,
                            Miles = 136,
                            Name = "Mount Rainer National Park",
                            State = "Washington"
                        },
                        new
                        {
                            ParkId = 14,
                            Miles = 3484,
                            Name = "Dry Tortugas National Park",
                            State = "Florida"
                        });
                });

            modelBuilder.Entity("ParksAPI.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<string>("Token");

                    b.Property<string>("Username");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
